### ISSUE TITLE
EPIC: Plastic Credit Marketplace

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#404]
# Background/Context

We need a basic marketplace for the plastic credits. We don't necessarily want to 

# Task to be done

```[tasklist]
### Planning
- [x] Decide on native module vs CosmWasm (Result: [CosmWasm](https://github.com/EmpowerPlastic/empowerchain/blob/main/chain/CODING_GUIDELINES.md#native-modules-vs-smart-contracts))
- [x] #418 
- [x] #423
- [ ] #493 
```

```[tasklist]
### Design
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/421
```

```[tasklist]
### Implementation
- [x] #426
- [ ] #394
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/507
- [ ] #434
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/531
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/532
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/548
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/551
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/546
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/556
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/539
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/589
- [x] Add frontend tasks
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/608
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/609
```

Other potential ones:
- Other queries?

**Comment by ba1ciu** [comment]
Actually it depends. Off-chain cache is modeled in a way that it returns already nicely formatted data. Not sure if it's the safest way to open Apollo server for querying directly from the client or should we have a backend proxy for that. If it's just read permission, it should be ok to just set up some dos prevention and open it publicly.
Also, question is if we need some non-chain features like user account, which would need additional database? If not, then I think that it's purely frontend+chain+off-chain cache.

**Comment by gjermundgaraba** [comment]
Yeah I don't think we need any non-chain features in the first iteration, so should be fine. Will the server also be able to handle search queries or do we need additional indexing for that?

**Comment by ba1ciu** [comment]
We'll be able to handle GraphQL queries just fine

**Comment by gjermundgaraba** [comment]
Yes, but will it handle full-text searches?

**Comment by ba1ciu** [comment]
I'll check it out!

**Comment by ba1ciu** [comment]
We should be good to use `ILIKE` operator and search all the fields at first. It's not going to handle fuzzy search, typos, etc.

Later if we want to make search smart we can either use `pg_trgm` and write Postgres functions or go with an additional indexer like Algolia or Lunr.js.

**Comment by gjermundgaraba** [comment]
Another alternative I've deployed before which is pretty easy too: https://typesense.org

**Comment by ba1ciu** [comment]
Closing!
