### ISSUE TITLE
EPIC: Proof of Existence

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#430]
```[tasklist]
### Frontend
- [x] #431
- [ ] #474
- [ ] #475
- [ ] #476
- [ ] #484
- [ ] #477
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/509
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/479
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/508
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/512
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/478
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/511
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/557
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/533
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/558
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/640
```

```[tasklist]
### Blockchain
- [ ] #383
```

```[tasklist]
### Backend
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4849
```
```[tasklist]
### Tasks
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/1129
```

**Comment by ba1ciu** [comment]
Note for later: let's discuss platform integration, so we can close this.
FYI @gjermundgaraba
