### ISSUE TITLE
EPIC: Road to mainnet

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#497]
Tracking misc tasks that are needed before mainnet:

```[tasklist]
### Technical
- [ ] #412
- [ ] #452
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/519
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/516
```

```[tasklist]
### Docs
- [ ] #8
- [ ] #16
- [ ] #18
- [ ] #332
- [ ] #7
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/553
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/607
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/616
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/617
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/618
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/619
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/620
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/621
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/622
```

```[tasklist]
### Testnets
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/555
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/554
```

Other concerns:
- Chain dashboard and explorer
-

**Comment by gjermundgaraba** [comment]
Closing as we have this and much more covered in #629
