### ISSUE TITLE
Marketplace e2e test setup

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#507]
Look into how we should run the e2e tests and set up the tests (including CI).

- Our own existing chain e2e framework (the one based on the Cosmos SDK)
- Osmosis test tube
- Abstract OS Boot
- Interchaintest (previously called "ibctest")

```[tasklist]
### Tasks
- [x] Decide e2e approach/framework
- [x] Implement setup and perhaps at least one test
- [x] Make sure it runs in CI
```

**Comment by gjermundgaraba** [comment]
Report on each solution:

### Osmosis test tube
Looks good, but requires a lot of setup to be able to connect to your own chain. In particular, you need to essentially do this: https://github.com/osmosis-labs/test-tube/tree/main/packages/osmosis-test-tube/libosmosistesttube

The main benefit of test tube is that it allows you to write e2e smart contract tests in Rust. The main drawback is the amount of extra code you need and the need to maintain it. 

Conclusion: ❌ No. 
Not worth it just to get the tests in Rust. We know Go, we like Go.

### Abstract OS Boot
I think this has potential, but it is very young, undocumented and unclear how we would work with our own chain (because we need to actually run some transactions on the native modules too). There also seems like there is a substantial amount of setup code to get things wired up. I don't love that.

The main benefit of test tube is that it allows you to write e2e smart contract tests in Rust. The main drawback is that it is too new and the amount of extra code you need and the need to maintain it.

It might be worth it for unit testing of the contracts, but not in its current undocumented form.

Conclusion: ❌ No. 
Not worth it just to get the tests in Rust.

### Our own existing chain e2e framework
Based on (and reusing a lot from) the Cosmos SDK e2e testing framework, we can probably do everything we need here, with the exception of any IBC-related things. Which we don't need right now either for the marketplace smart contract testing.

Main benefit: It works. It's already there. We know it. 
Main drawback: Very disconnected from the Rust code. No IBC.

Conclusion: Maybe / Not fully decided yet.

### Interchaintest
TBD

This comment we be updated as I complete this task
