### ISSUE TITLE
Create mainnet genesis in code

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#519]
Create a new command or something that creates a realistic mainnet genesis (to the extent we know right now).

Context: to keep automated and manual testing of the real genesis consistent + we can develop our genesis file creation directly in code and therefore have nice versioning.

Osmosis seems to have done something a bit similar: https://github.com/osmosis-labs/osmosis/blob/main/cmd/osmosisd/cmd/genesis.go

```[tasklist]
### Tasks
- [x] Create a reusable function that returns the genesis (in a form that can be modified, for tests and stuff)
- [x] Create a (cli) command for creating the genesis file
- [x] Change tests to start using the new genesis as a basis
- [x] Prepare genesis module params
```

**Comment by ba1ciu** [comment]
Reopening as we till have to decide on mainnet module params.
