### ISSUE TITLE
Update to Earthly 0.7

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#520]
New version of Earthly is out, we need to:

```[tasklist]
### Tasks
- [ ] update Earthfile's with `VERSION 0.7`
- [ ] update Earthly github action versions to 0.7.0 (or newer dot version if available)
- [ ] make sure all pipelines are still OK
```

**Comment by ba1ciu** [comment]
Very low priority.
