### ISSUE TITLE
EPIC: Launch plan

### ISSUE THREAD

**Issue by ba1ciu** [EmpowerPlastic/empowerchain#629]
```[tasklist]
### Pre-preparation (24-30 April)
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/561
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/523
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4138
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/609
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/632
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/634
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/637
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/649
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/663
```
```[tasklist]
### Core backend (1-21 May)
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4141
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/608
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4137
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4139
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4140
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4144
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4237
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4270
- [x] Enable update org pubsub subscription in QA with terraform
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4391
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4392
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4655
```
```[tasklist]
### Core frontend - Platform (1-28 May)
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/3896
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4178
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4179
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4180
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4181
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4182
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4183
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4184
```
```[tasklist]
### Core frontend - Marketplace (1-28 May)
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/630
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/650
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/651
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/652
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/653
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/654
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/655
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/656
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/657
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/658
```
```[tasklist]
### Testnet preparation (15-28 May)
- [x] Select validators for testnet gentx
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/700
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/519
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/554
- [x] Create spreadsheet with tasks and challenges for rewards
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/638
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/636
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/779
```
```[tasklist]
### Testnet launch (29 May - 4 June)
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/701
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/616
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/617
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/622
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/640
- [x] Launching network
- [x] Deploying and hooking up Marketplace and Empower Platform update
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/809
```
```[tasklist]
### Testnet phase / Mainnet prep (5 - 25 June)
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/641
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/618
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/619
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/620
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/621
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4389
- [ ] Finishing up core frontend and backend leftovers
- [ ] Go-to-market/some/launch strategy
- [x] Fixing bugz
- [ ] Collecting gentxs for mainnet
- [ ] Preparing mainnet genesis
- [ ] Make nicer doc images (get a designer to fix up all the ugly images)
- [ ] Integrate external IPFS gateway with our own IPFS cluster?
- [ ] Create script to check PoE status from platform
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/516
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/607
- [ ] #399
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4381
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/696
- [ ] Set up a discourse forum for governance (or something similar)
- [x] Airdrops scripts + into mainnet genesis (if any)
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/804
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/822
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/959
```
```[tasklist]
### Frontend tweaks and fixes to do during testnet phase (5 - 25 June)
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/639
- [ ] #558
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/806
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/807
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/808
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/810
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/814
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/827
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/828
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/840
```
```[tasklist]
### Mainnet launch 🚀  (26 - 30 June)
- [x] Mainnet launch 🚀 🚀
- [ ] Empower Platform prod update
- [ ] Marketplace prod deployment
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/639
```
```[tasklist]
### Later / if we get time (lol)
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4189
- [ ] #487
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/678
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/659
- [ ] CLI query for applicants
- [ ] CLI query for projects
- [ ] CLI query for project by applicant id
- [ ] Certificates module docs + add to docs site
- [ ] https://github.com/EmpowerPlastic/empower-platform/issues/4398
- [ ] Implement a queue system for PoE
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/937
```

**Comment by ba1ciu** [comment]
Note for later: Let's discuss what's still needed to be done as a part of launch. Prod deployments, anything else?
FYI @gjermundgaraba

**Comment by ba1ciu** [comment]
To be closed when first credits are migrated to mainnet and marketplace is working
