### ISSUE TITLE
Docs + references necessary for pre-testnet challenges

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#637]
Depends on: #634

```[tasklist]
### Tasks
- [x] Document empowerchain architecture
- [x] Developer high level docs
- [x] Plastic credits high level docs (use/reuse module docs?)
- [x] PoE high level docs (use/reuse module docs?)
```
