### ISSUE TITLE
Test Genesis

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#959]
Things to test/check:

```[tasklist]
### Tasks
- [x] Total tokens are correct
- [x] Groups are set up with the correct type of accounts and the correct amount of tokens (check lock and vesting for those where that is relevant)
- [x] Inflation is off
- [x] IBC (transfer and ICA) is off
- [x] Governance params are correct
- [x] Slashing params are correct
- [x] Wasm works
- [x] Staking params are correct
- [x] Collect gentx works on it
```
