### ISSUE TITLE
EPIC: Plastic Credit Registry

### ISSUE THREAD

**Issue by ba1ciu** [EmpowerPlastic/empowerchain#998]
```[tasklist]
### Tasks
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/999
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/1000
- [ ] https://github.com/EmpowerPlastic/empowerchain/issues/1001
- [ ] more to come..
```
